-- ========================================================
-- SKRIP SETUP DATABASE SUPABASE UNTUK APLIKASI PKK ALSKY
-- ========================================================
-- Jalankan skrip ini di SQL Editor di Dashboard Supabase Anda
-- (Dashboard Supabase > SQL Editor > New Query > Paste & Run)

-- 1. TABEL USERS (Data Pengguna & Karyawan)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nip TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    nama TEXT NOT NULL,
    level TEXT NOT NULL,
    jabatan TEXT NOT NULL,
    unit TEXT NOT NULL,
    atasan1 TEXT,
    atasan2 TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index untuk pencarian NIP super cepat
CREATE INDEX IF NOT EXISTS idx_users_nip ON public.users(nip);

-- 2. TABEL SKIS (Template SKI & Indikator Kinerja)
CREATE TABLE IF NOT EXISTS public.skis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_nip TEXT,
    target_unit TEXT,
    target_level TEXT,
    target_jabatan TEXT,
    kpi_departemen TEXT,
    ski TEXT,
    target_detail TEXT,
    kriteria1 TEXT,
    kriteria2 TEXT,
    kriteria3 TEXT,
    kriteria4 TEXT,
    kriteria5 TEXT,
    bobot NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index untuk filter target jabatan & unit SKI
CREATE INDEX IF NOT EXISTS idx_skis_target ON public.skis(target_unit, target_level, target_jabatan);

-- 3. TABEL PKKS (Penilaian Kinerja Karyawan & Evaluasi Mandiri)
CREATE TABLE IF NOT EXISTS public.pkks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nip TEXT NOT NULL,
    nama TEXT NOT NULL,
    unit TEXT NOT NULL,
    tahun_ajaran TEXT,
    final_score NUMERIC DEFAULT 0,
    final_grade TEXT,
    status TEXT DEFAULT 'Draft',
    tanggal TEXT,
    evaluasi_data JSONB,
    verifikasi1_data JSONB,
    verifikasi2_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pkks_nip ON public.pkks(nip);
CREATE INDEX IF NOT EXISTS idx_pkks_status ON public.pkks(status);

-- 4. TABEL TAHUN_AJARAN (Pengaturan Tahun Ajaran Aktif)
CREATE TABLE IF NOT EXISTS public.tahun_ajaran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tahun TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Tidak Aktif',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABEL BOBOT (Pengaturan Bobot Penilaian per Jabatan)
CREATE TABLE IF NOT EXISTS public.bobot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jabatan TEXT UNIQUE NOT NULL,
    kpi NUMERIC DEFAULT 0,
    perilaku NUMERIC DEFAULT 0,
    manajerial NUMERIC DEFAULT 0
);

-- 6. TABEL PENGUMUMAN (Pengumuman Dashboard)
CREATE TABLE IF NOT EXISTS public.pengumuman (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    deskripsi TEXT,
    tanggal TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES (AKSES ANONYMOUS / PUBLIC)
-- ========================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pkks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tahun_ajaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bobot ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengumuman ENABLE ROW LEVEL SECURITY;

-- Izinkan akses Read/Write untuk aplikasi web client
CREATE POLICY "Allow public read/write users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write skis" ON public.skis FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write pkks" ON public.pkks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write tahun_ajaran" ON public.tahun_ajaran FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write bobot" ON public.bobot FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write pengumuman" ON public.pengumuman FOR ALL USING (true) WITH CHECK (true);

-- ========================================================
-- DATA INITIAL SEED (DATA AWAL CONTOH UNTUK USERS & BOBOT)
-- ========================================================
INSERT INTO public.users (nip, password, nama, level, jabatan, unit, atasan1, atasan2) VALUES
('1001', '123', 'Super Admin', 'Super Admin', 'Admin', 'Pusat', '', ''),
('0885.0220.00', '0885.0220.00', 'Ahmad Abdul Wasiudin, M.Pd', 'General Manager', 'GM Pendidikan', 'Direksi', '', ''),
('0884.0710.00', '0884.0710.00', 'Dina Fitriani, S.Pt', 'General Manager', 'GM Operasional', 'Direksi', '', '')
ON CONFLICT (nip) DO NOTHING;

INSERT INTO public.tahun_ajaran (tahun, status) VALUES
('2024/2025', 'Tidak Aktif'),
('2025/2026', 'Aktif')
ON CONFLICT (tahun) DO NOTHING;

INSERT INTO public.bobot (jabatan, kpi, perilaku, manajerial) VALUES
('Staff', 70, 30, 0),
('Pelaksana', 70, 30, 0),
('Tim Leader', 60, 20, 20),
('Supervisor', 60, 20, 20),
('Manager', 50, 30, 20),
('General Manager', 50, 30, 20),
('Direktur', 40, 30, 30)
ON CONFLICT (jabatan) DO NOTHING;
